### PR TITLE
refactor(useShape): replace effect+state with useSyncExternalStoreWithSelector

### PR DESCRIPTION
**Pull request by rortan134**
This PR refactors the `useShape` hook to leverage [useSyncExternalStore](https://react.dev/reference/react/useSyncExternalStore) since it is ideal for such external (non-react) data synchronization, and having an additional server snapshot that the previous initial state of `useState` didn't cover

Also opens the possibility for some hook-level caching ([example](https://github.com/vercel/swr/blob/1585a3e37d90ad0df8097b099db38f1afb43c95d/src/core/use-swr.ts#L177-L263))

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmm yes you're right — this is better.

It'd also make a lot of use to use `useSyncExternalStoreWithSelector` as it'll be pretty common to have a large shape syncing into an app but a particular component will only care about a subset of those e.g. the latest 10 projects vs. all 500. So allowing a selector would reduce extra renders.

**Comment by KyleAMathews** [comment]
It looks like the a test is failing

**Comment by rortan134** [comment]
> It'd also make a lot of sense to use `useSyncExternalStoreWithSelector` as it'll be pretty common to have a large shape syncing into an app but a particular component will only care about a subset of those e.g. the latest 10 projects vs. all 500. So allowing an optional selector would reduce extra renders.

Agreed. How should such API be exposed to the user?

**Comment by KyleAMathews** [comment]
It'd just be another argument passed to `useShape` which is then passed to `useSyncExternalStoreWithSelector`.

**Comment by KyleAMathews** [comment]
Why not use the built in one? 

https://github.com/facebook/react/blob/66df94460e27ff382c07b13d0bcc4b2778bfc201/packages/use-sync-external-store/src/useSyncExternalStoreWithSelector.js

It was introduced in React 18 I believe. If people want support for older reacts we could later add support for letting people pass in the 3rd party lib.

**Comment by rortan134** [comment]
> Why not use the built in one? 
> 
> https://github.com/facebook/react/blob/66df94460e27ff382c07b13d0bcc4b2778bfc201/packages/use-sync-external-store/src/useSyncExternalStoreWithSelector.js
> 
> It was introduced in React 18 I believe. If people want support for older reacts we could later add support for letting people pass in the 3rd party lib.

It isn't exported by [default](https://github.com/facebook/react/blob/main/packages/react/index.js) from `react`, the code you referenced is this official library. 

This is the modern version 18 though, to support older react versions you'd need to import from `use-sync-external-store/shim/with-selector`

**Comment by KyleAMathews** [comment]
Ah ok, my bad.

Most of the team is in Europe so I'll let them check this out Monday but 👍 from me for merging.

**Comment by KyleAMathews** [comment]
Actually with adding the new `selector` api, it'd be good to have a test for that as well

**Review by KyleAMathews — APPROVED** [review]
great work @rortan134! Thanks for the fix.

**Pull request merged**
